# Docs: <https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/customizing-dependency-updates>

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: 'tuesday'
      time: '01:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 30

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: 'tuesday'
      time: '01:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: 'tuesday'
      time: '01:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 10
