name: 💡 Feature Request
description: Suggest an idea

body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: A clear description of the problem this feature would solve
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: A clear description of what change you would like
      placeholder: 'I would like to...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Any alternative solutions you've considered"

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

  - type: markdown
    attributes:
      value: |
        ### Can I suggest web3 stuff?

        Pony House is a chat app, not a crypto marketplace, if you are wanting to go against these suggestion rules then I recommend you open an independent repository to develop a mod related to this instead of suggesting in this base repository. The client itself already has related docs on how to develop mods. Feel free to create mods and share them on the internet, but always leave a disclaimer that I am not responsible for these mods.

        When suggesting things related to web3 to the native client. Avoid the following things:

        - General NFTs (I make an exception only for web3 domains that are trustworthy)
        - Any crypto token that is not a dollar stablecoin or a blockchain's native cryptocurrency.
        - Proxy smart contracts (Smart contracts that can be updated by the smart contract editor). I make exceptions only for dollar stablecoin smart contracts.
        - Any feature that attempts to turn Pony House into a Pay-To-Win application using crypto.

        By breaking one of these rules, you agree that your issue will be closed without notice.
