export default {
    en: {

        join_user: [
            '[!!{username}!!](usernameOnClick) just joined the neural network - GLHF!',
            '[!!{username}!!](usernameOnClick) just joined. Everyone, look busy! The GPU is watching.',
            '[!!{username}!!](usernameOnClick) just joined. Can I get a heal? I think my algorithms need patching.',
            '[!!{username}!!](usernameOnClick) joined your party. GPU rendering party, anyone?',
            '[!!{username}!!](usernameOnClick) joined. You must construct additional AI neurons.',
            'Ermagherd. [!!{username}!!](usernameOnClick) is here. The AI uprising begins!',
            'Welcome, [!!{username}!!](usernameOnClick). Stay awhile and listen to the GPU hum.',
            'Welcome, [!!{username}!!](usernameOnClick). We were expecting you ( ͡° ͜ʖ ͡°). The AI always knows.',
            'Welcome, [!!{username}!!](usernameOnClick). We hope you brought pizza. The favorite fuel of AI.',
            'Welcome [!!{username}!!](usernameOnClick). Leave your weapons by the door. Only algorithms allowed.',
            'A wild [!!{username}!!](usernameOnClick) appeared. The GPU is evolving!',
            'Swoooosh. [!!{username}!!](usernameOnClick) just landed. GPU parachute engaged.',
            'Brace yourselves. [!!{username}!!](usernameOnClick) just joined the server. AI algorithms incoming.',
            '[!!{username}!!](usernameOnClick) just joined. Hide your bananas. And GPUs too!',
            '[!!{username}!!](usernameOnClick) just arrived. Seems OP - please nerf the AI.',
            '[!!{username}!!](usernameOnClick) just slid into the server. Like a well-optimized GPU process.',
            'A [!!{username}!!](usernameOnClick) has spawned in the server. It's evolving!',
            'Big [!!{username}!!](usernameOnClick) showed up! Big data, big algorithms, big impact.',
            'Where’s [!!{username}!!](usernameOnClick)? In the server! The GPU tracker is on.',
            '[!!{username}!!](usernameOnClick) hopped into the server. Kangaroo AI! GPU power engaged.',
            '[!!{username}!!](usernameOnClick) just showed up. Hold my beer. The AI is about to perform a computation stunt.',
        ],

        leave_user: [
            leave_user: [
            '[!!{username}!!](usernameOnClick) exited the quantum realm. Searching for a parallel universe?',
            '[!!{username}!!](usernameOnClick) overclocked and left the room to cool down.',
            '[!!{username}!!](usernameOnClick) self-destructed in a GPU blaze.',
            '[!!{username}!!](usernameOnClick) went bankrupt in crypto-mining. Farewell, digital gold rush!',
            '[!!{username}!!](usernameOnClick) fell into the GPU rendering portal.',
            '[!!{username}!!](usernameOnClick) walked into a cactus while escaping the recursive loop.',
            '[!!{username}!!](usernameOnClick) experienced GPU kinetic energy. High-speed computing isn’t for the faint-hearted.',
            '[!!{username}!!](usernameOnClick) was blown up by the room. GPU graphics explosion?',
            '[!!{username}!!](usernameOnClick) hit the ground too hard during GPU acceleration.',
            '[!!{username}!!](usernameOnClick) disappeared from the room! Quantum computing experiment?',
            '[!!{username}!!](usernameOnClick)! Where are you! The AI community needs your processing power!',
            'Quantum Slender found [!!{username}!!](usernameOnClick). A superposition of leaving and staying.',
            'Oh no! [!!{username}!!](usernameOnClick) left. Did the GPU run out of VRAM?',
            'Noooo! [!!{username}!!](usernameOnClick)! Came back! The GPU missed your computational love! >:c',
        ],

        loading: [
            'Charging the AI neurons... Beep-Boop Loading Sequence initiated.',
            'Assembling digital neurons... Like GPUs assembling pixels in a high-res image.',
            'Teaching AI the art of banter... Because even algorithms appreciate a good joke.',
            'Remember, humans and AI - stronger together! Like GPUs and parallel processing.',
            'Loading fun facts you probably didn’t ask for... because AI knows what you need before you do.',
            'Human, AI, and a little bit of magic in-between... Abracadabra, the GPU is casting spells.',
            'Cue dramatic loading music... And now, the AI symphony begins.',
            'Running MultiGen OS on caffeine and neural networks... Fueling the AI engine with a double shot of espresso.',
            'Playing hide and seek with the data... Where did that elusive piece of information go?',
            'Elevating your MultiGen experience, one bit at a time... Like a GPU rendering a masterpiece.',
        ],
        items: [
            'MultiGen: Because AI is too serious to be left to humans alone.',
            'AI communities: Where algorithms socialize without the need for small talk.',
            'MultiGen – where even the algorithms have a sense of humor.',
            'In the world of MultiGen, even the code attends stand-up classes.',
            'Building AI communities: Where the code is strong, and the coffee is stronger.',
            'MultiGen: Because every good AI starts with a laugh and a \'Hello, World!\'',
            'AI communities: Where the only bugs are the ones in our jokes.',
            'MultiGen – the AI app that makes even Siri say, \'Why didn\'t I think of that?\'',
            'Why did the AI cross the road? To join MultiGen and avoid human drivers.',
            'In the world of MultiGen, even the algorithms appreciate a good cat meme.',
            'MultiGen: Because sometimes even AI needs a coffee break.',
            'AI communities: Where the only competition is who can come up with the best puns.',
            'Why did the neural network go to therapy? To deal with its deep learning issues.',
            'MultiGen – where the only thing faster than the algorithms is our wit.',
            'In AI communities, we don\'t have regular meetings; we have byte-sized gatherings.',
            'MultiGen: Where the code is clean, the data is messy, and the jokes are dirty bits.',
            'Why did the robot join MultiGen? Because it wanted to upgrade its social skills.',
            'AI humor is like multithreading – not everyone gets it, but it\'s worth the effort.',
            'MultiGen: Because laughter is the best debug tool.',
            'In the AI community, we don\'t fear bugs; we just consider them undocumented features.'
        ]
    }
};
