export default {
  en: {
    join_user: [
      '[!!{username}!!](usernameOnClick) just pixelated into the party - get ready for some pixel-perfect fun!',
      '[!!{username}!!](usernameOnClick) just joined. Pixel party alert! Grab your creative snacks.',
      '[!!{username}!!](usernameOnClick) entered the creative matrix. Can I get a pixel-high five?',
      '[!!{username}!!](usernameOnClick) joined your pixel party. Time to paint the town with creativity!',
      '[!!{username}!!](usernameOnClick) just landed. You must construct additional pixels.',
      'Ermagherd. [!!{username}!!](usernameOnClick) is here. The Pixxel chaos is about to begin!',
      'Welcome, [!!{username}!!](usernameOnClick). Stay awhile and witness the magic of evolving Pixxels.',
      'Welcome, [!!{username}!!](usernameOnClick). We were expecting you ( ͡° ͜ʖ ͡°). The Pixxels always know.',
      'Welcome, [!!{username}!!](usernameOnClick). We hope you brought snacks. Pixxels love snacks.',
      'Welcome [!!{username}!!](usernameOnClick). Leave your pixels by the door. Only creative coding allowed.',
      'A wild [!!{username}!!](usernameOnClick) appeared. The Pixxel evolution is in progress!',
      'Swoooosh. [!!{username}!!](usernameOnClick) just landed. Pixxel parachute engaged.',
      'Brace yourselves. [!!{username}!!](usernameOnClick) just joined the server. Pixxel masterpieces incoming.',
      '[!!{username}!!](usernameOnClick) just joined. Hide your brushes. And your GPUs too!',
      '[!!{username}!!](usernameOnClick) just arrived. Seems OP - please nerf the Pixxels.',
      '[!!{username}!!](usernameOnClick) just slid into the server. Like a well-optimized pixel process.',
      'A [!!{username}!!](usernameOnClick) has spawned in the server. It is evolving!',
      'Big [!!{username}!!](usernameOnClick) showed up! Big pixels, big creativity, big impact.',
      'Where’s [!!{username}!!](usernameOnClick)? In the server! The Pixxel tracker is on.',
      '[!!{username}!!](usernameOnClick) hopped into the server. Kangaroo Pixxel! Creativity engaged.',
      '[!!{username}!!](usernameOnClick) just showed up. Hold my paintbrush. The Pixxel artistry is about to begin.',
    ],

    leave_user: [
      '[!!{username}!!](usernameOnClick) pixelated out of existence. Looking for a parallel canvas?',
      '[!!{username}!!](usernameOnClick) pixelated and left the frame to cool down. Canvas cooling in progress.',
      '[!!{username}!!](usernameOnClick) self-destructed in a Pixxel blaze. Creative explosion?',
      '[!!{username}!!](usernameOnClick) went bankrupt in creative mining. Farewell, digital masterpiece rush!',
      '[!!{username}!!](usernameOnClick) fell into the Pixxel portal. Abstract exit strategy in action.',
      '[!!{username}!!](usernameOnClick) walked into a color palette while escaping the recursive loop.',
      '[!!{username}!!](usernameOnClick) experienced Pixxel kinetic energy. High-speed creativity isn’t for the faint-hearted.',
      '[!!{username}!!](usernameOnClick) was blown up by inspiration. Pixxel imagination explosion?',
      '[!!{username}!!](usernameOnClick) hit the canvas too hard during creative acceleration.',
      '[!!{username}!!](usernameOnClick) disappeared from the frame! Quantum artistry experiment?',
      '[!!{username}!!](usernameOnClick)! Where are you! The Pixxel community needs your creative power!',
      'Quantum Painter found [!!{username}!!](usernameOnClick). A superposition of leaving and staying.',
      'Oh no! [!!{username}!!](usernameOnClick) left. Did the Pixxel palette run out of colors?',
      'Noooo! [!!{username}!!](usernameOnClick)! Came back! The Pixxels missed your creative touch! >:c',
    ],

    loading: [
      'Charging the Pixxel fun generators... Beep-Boop Loading Laughter Sequence initiated.',
      'Assembling digital pixels in the vast expanse of Pixxelville... Like an artist arranging pixels for a creative masterpiece.',
      'Teaching Pixxels the art of creative banter... Because even algorithms in Pixxelville appreciate a joke that transcends canvases.',
      'Remember, humans and Pixxels - creating together! Like artistic forces and parallel processing.',
      'Loading fun facts from the creative universe you probably didn’t ask for... because Pixxels know what you need before you do.',
      'Human, Pixxels, and a little bit of artistic magic in-between... Abracadabra, the brush is casting creative spells.',
      'Cue dramatic loading music from across the creative universe... And now, the Pixxel Symphony of Awesomeness begins.',
      'Running Pixxel OS on caffeine and neural networks... Fueling the creativity engine with a double shot of artistic espresso.',
      'Playing hide and seek with the pixels in the vastness of Pixxelville... Where did that elusive piece of creative inspiration go?',
      'Elevating your Pixxel experience, one creative bit at a time... Like an artist rendering a masterpiece in the creative gallery.',
    ],

    items: [
      'Pixxel Communities: Because creativity deserves a pixelated stage and a roaring virtual audience.',
      'Community Pixelations: Where code collaborates without the burden of mundane talk, fueled by the laughter of Pixxels.',
      'Pixxel Communities – where even the algorithms have a flair for comedic collaboration.',
      'In the world of Pixxel Communities, even the code attends stand-up classes for a good laugh.',
      'Building creative communities: Where the code is robust, and the coffee is robustly brewed, all within the vibrant realm of Pixxels.',
      'Pixxel Communities: Because every remarkable artwork starts with a chuckle and a "Hello, Community!"',
      'Community Pixelations: Where the only bugs are the ones in our community jokes, and they are welcomed with open virtual arms.',
      'Pixxel Communities – the app that makes even Siri say, "Why dont I think of that for my virtual hangout?"',
      'Why did the artist cross the road? To join Pixxel Communities and dodge mundane landscapes in favor of creative collaborations.',
      'In the world of Pixxel Communities, even the algorithms appreciate a good community meme.',
      'Pixxel Communities: Because sometimes even creativity needs a virtual coffee break shared with like-minded pixel enthusiasts.',
      'Community Pixelations: Where the only competition is who can come up with the best visual puns, uniting Pixxels in laughter.',
      'Why did the paintbrush go to therapy? To address its deep blending issues with the supportive Pixxel Communities.',
      'Pixxel Communities – where the only thing quicker than the algorithms is our artistic wit, shared and celebrated within the community.',
      'In creative communities, we dont have regular meetings; we have stroke-sized gatherings, painting the canvas of our Pixxel adventures.',
      'Pixxel Communities: Where the code is clean, the canvas is messy with creativity, and the jokes are cheeky bits of shared laughter.',
      'Why did the robot join Pixxel Communities? To upgrade its social skills, embrace virtual camaraderie, and share in the joy of collaborative pixel artistry.',
      'Pixxel Communities humor is like multithreading – not everyone gets it, but its worth the effort to connect and laugh together.',
      'Pixxel Communities: Because laughter is the best debug tool in the collaborative world of creative minds.',
      'In the Pixxel Communities, we dont fear bugs; we just consider them unique features, adding character to our shared creative space.',
    ]
  }
};
